### ISSUE TITLE
[Bug] 是否支持 h2 + reality?

### ISSUE THREAD

**Issue by fscarmen** [MerlinKodo/clash-rev#4]
### 先决条件

- [X] 我了解这里是开源版 Clash.Rev 核心仓库
- [X] 我要提交 Clash.Rev 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash.Rev 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://merlinkodo.github.io/clash-rev-doc/) 并无法自行解决问题

### 版本

V1.16 (meta 最后的版本）

### 适用的作业系统

macOS (darwin)

### 适用的硬件架构

amd64

### 配置文件

```YAML
服务端用 sing-box version 1.7.0-beta.3 ，以下的配置，在 v2rayN （Xray 内核) / 小火箭 / nekoray (sing-box 内核）/ Sing-box 客户端均可以连接，唯独万能的 meta 不行

{
    "inbounds":[
        {
            "type":"vless",
            "sniff":true,
            "sniff_override_destination":true,
            "tag":"h2-reality-in",
            "listen":"::",
            "listen_port":10008,
            "users":[
                {
                    "uuid":"31cfa9ec-577b-4cab-83a2-bd0f9058606b"
                }
            ],
            "tls":{
                "enabled":true,
                "server_name":"addons.mozilla.org",
                "reality":{
                    "enabled":true,
                    "handshake":{
                        "server":"addons.mozilla.org",
                        "server_port":443
                    },
                    "private_key":"EOIt2itwfHMQCUsddX--jeQ7vpGETcneF0XjZc3Ap18",
                    "short_id":[
                        ""
                    ]
                }
            },
            "transport": {
                "type": "http"
            },
            "multiplex":{
                "enabled":true,
                "padding":true,
                "brutal":{
                    "enabled":true,
                    "up_mbps":1000,
                    "down_mbps":1000
                }
            }
        }
    ]
}
```

clash meta
```
  - name: "hax vless-reality-h2"
    type: vless
    server: 2602:294:0:dc:1234:1234:c473:1
    port: 10008
    uuid: 31cfa9ec-577b-4cab-83a2-bd0f9058606b
    network: h2
    tls: true
    udp: true
    flow:
    client-fingerprint: chrome
    servername: addons.mozilla.org
    h2-opts:
      host: 
        - ""
      path: /
    reality-opts:
      public-key: jwn2eixWlHm6Vg-pq49w7AT_vgIa6vxtg846gfTZJB8
      short-id: ""
```
```


### 日志输出

_No response_

### 问题描述

连不通

### 复现步骤

_No response_
